// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: activity/activity.proto

package activity

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrackBenchPressV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TrackBenchPressV1Response) Reset() {
	*x = TrackBenchPressV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activity_activity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackBenchPressV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackBenchPressV1Response) ProtoMessage() {}

func (x *TrackBenchPressV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackBenchPressV1Response.ProtoReflect.Descriptor instead.
func (*TrackBenchPressV1Response) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{0}
}

type TrackBenchPressV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId  uint64 `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	AccessToken string `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Repeats     uint32 `protobuf:"varint,3,opt,name=repeats,proto3" json:"repeats,omitempty"`
}

func (x *TrackBenchPressV1Request) Reset() {
	*x = TrackBenchPressV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activity_activity_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackBenchPressV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackBenchPressV1Request) ProtoMessage() {}

func (x *TrackBenchPressV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackBenchPressV1Request.ProtoReflect.Descriptor instead.
func (*TrackBenchPressV1Request) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{1}
}

func (x *TrackBenchPressV1Request) GetActivityId() uint64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *TrackBenchPressV1Request) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TrackBenchPressV1Request) GetRepeats() uint32 {
	if x != nil {
		return x.Repeats
	}
	return 0
}

type TrackPullUpsV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId  uint64 `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	AccessToken string `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Repeats     uint32 `protobuf:"varint,3,opt,name=repeats,proto3" json:"repeats,omitempty"`
}

func (x *TrackPullUpsV1Request) Reset() {
	*x = TrackPullUpsV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activity_activity_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackPullUpsV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackPullUpsV1Request) ProtoMessage() {}

func (x *TrackPullUpsV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackPullUpsV1Request.ProtoReflect.Descriptor instead.
func (*TrackPullUpsV1Request) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{2}
}

func (x *TrackPullUpsV1Request) GetActivityId() uint64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *TrackPullUpsV1Request) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TrackPullUpsV1Request) GetRepeats() uint32 {
	if x != nil {
		return x.Repeats
	}
	return 0
}

type TrackPullUpsV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TrackPullUpsV1Response) Reset() {
	*x = TrackPullUpsV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activity_activity_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackPullUpsV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackPullUpsV1Response) ProtoMessage() {}

func (x *TrackPullUpsV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackPullUpsV1Response.ProtoReflect.Descriptor instead.
func (*TrackPullUpsV1Response) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{3}
}

type TrackCyclingV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TrackCyclingV1Response) Reset() {
	*x = TrackCyclingV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activity_activity_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackCyclingV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackCyclingV1Response) ProtoMessage() {}

func (x *TrackCyclingV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackCyclingV1Response.ProtoReflect.Descriptor instead.
func (*TrackCyclingV1Response) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{4}
}

type TrackCyclingV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId  uint64 `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	AccessToken string `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Metres      uint32 `protobuf:"varint,3,opt,name=metres,proto3" json:"metres,omitempty"`
}

func (x *TrackCyclingV1Request) Reset() {
	*x = TrackCyclingV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activity_activity_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackCyclingV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackCyclingV1Request) ProtoMessage() {}

func (x *TrackCyclingV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackCyclingV1Request.ProtoReflect.Descriptor instead.
func (*TrackCyclingV1Request) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{5}
}

func (x *TrackCyclingV1Request) GetActivityId() uint64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *TrackCyclingV1Request) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TrackCyclingV1Request) GetMetres() uint32 {
	if x != nil {
		return x.Metres
	}
	return 0
}

type TrackCrunchesV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId  uint64 `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	AccessToken string `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Repeats     uint32 `protobuf:"varint,3,opt,name=repeats,proto3" json:"repeats,omitempty"`
}

func (x *TrackCrunchesV1Request) Reset() {
	*x = TrackCrunchesV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activity_activity_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackCrunchesV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackCrunchesV1Request) ProtoMessage() {}

func (x *TrackCrunchesV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackCrunchesV1Request.ProtoReflect.Descriptor instead.
func (*TrackCrunchesV1Request) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{6}
}

func (x *TrackCrunchesV1Request) GetActivityId() uint64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *TrackCrunchesV1Request) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TrackCrunchesV1Request) GetRepeats() uint32 {
	if x != nil {
		return x.Repeats
	}
	return 0
}

type TrackCrunchesV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TrackCrunchesV1Response) Reset() {
	*x = TrackCrunchesV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activity_activity_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackCrunchesV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackCrunchesV1Response) ProtoMessage() {}

func (x *TrackCrunchesV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackCrunchesV1Response.ProtoReflect.Descriptor instead.
func (*TrackCrunchesV1Response) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{7}
}

type TrackPushUpV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId  uint64 `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	AccessToken string `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Repeats     uint32 `protobuf:"varint,3,opt,name=repeats,proto3" json:"repeats,omitempty"`
}

func (x *TrackPushUpV1Request) Reset() {
	*x = TrackPushUpV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activity_activity_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackPushUpV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackPushUpV1Request) ProtoMessage() {}

func (x *TrackPushUpV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackPushUpV1Request.ProtoReflect.Descriptor instead.
func (*TrackPushUpV1Request) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{8}
}

func (x *TrackPushUpV1Request) GetActivityId() uint64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *TrackPushUpV1Request) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TrackPushUpV1Request) GetRepeats() uint32 {
	if x != nil {
		return x.Repeats
	}
	return 0
}

type TrackPushUpsV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TrackPushUpsV1Response) Reset() {
	*x = TrackPushUpsV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activity_activity_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackPushUpsV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackPushUpsV1Response) ProtoMessage() {}

func (x *TrackPushUpsV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackPushUpsV1Response.ProtoReflect.Descriptor instead.
func (*TrackPushUpsV1Response) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{9}
}

type GetActivityListV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
}

func (x *GetActivityListV1Request) Reset() {
	*x = GetActivityListV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activity_activity_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetActivityListV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityListV1Request) ProtoMessage() {}

func (x *GetActivityListV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityListV1Request.ProtoReflect.Descriptor instead.
func (*GetActivityListV1Request) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{10}
}

func (x *GetActivityListV1Request) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type GetActivityListV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityList []*ActivityMessage `protobuf:"bytes,1,rep,name=activity_list,json=activityList,proto3" json:"activity_list,omitempty"`
}

func (x *GetActivityListV1Response) Reset() {
	*x = GetActivityListV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activity_activity_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetActivityListV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityListV1Response) ProtoMessage() {}

func (x *GetActivityListV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityListV1Response.ProtoReflect.Descriptor instead.
func (*GetActivityListV1Response) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{11}
}

func (x *GetActivityListV1Response) GetActivityList() []*ActivityMessage {
	if x != nil {
		return x.ActivityList
	}
	return nil
}

type TrackStepsV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId  uint64 `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	AccessToken string `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Steps       uint32 `protobuf:"varint,3,opt,name=steps,proto3" json:"steps,omitempty"`
}

func (x *TrackStepsV1Request) Reset() {
	*x = TrackStepsV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activity_activity_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackStepsV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackStepsV1Request) ProtoMessage() {}

func (x *TrackStepsV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackStepsV1Request.ProtoReflect.Descriptor instead.
func (*TrackStepsV1Request) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{12}
}

func (x *TrackStepsV1Request) GetActivityId() uint64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *TrackStepsV1Request) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TrackStepsV1Request) GetSteps() uint32 {
	if x != nil {
		return x.Steps
	}
	return 0
}

type TrackStepsV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TrackStepsV1Response) Reset() {
	*x = TrackStepsV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activity_activity_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackStepsV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackStepsV1Response) ProtoMessage() {}

func (x *TrackStepsV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackStepsV1Response.ProtoReflect.Descriptor instead.
func (*TrackStepsV1Response) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{13}
}

type ActivityMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ActivityMessage) Reset() {
	*x = ActivityMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activity_activity_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivityMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityMessage) ProtoMessage() {}

func (x *ActivityMessage) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityMessage.ProtoReflect.Descriptor instead.
func (*ActivityMessage) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{14}
}

func (x *ActivityMessage) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ActivityMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_activity_activity_proto protoreflect.FileDescriptor

var file_activity_activity_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1b, 0x0a, 0x19, 0x54, 0x72, 0x61, 0x63, 0x6b,
	0x42, 0x65, 0x6e, 0x63, 0x68, 0x50, 0x72, 0x65, 0x73, 0x73, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x78, 0x0a, 0x18, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x42, 0x65, 0x6e,
	0x63, 0x68, 0x50, 0x72, 0x65, 0x73, 0x73, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49,
	0x64, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x73, 0x22, 0x75,
	0x0a, 0x15, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x50, 0x75, 0x6c, 0x6c, 0x55, 0x70, 0x73, 0x56, 0x31,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x72,
	0x65, 0x70, 0x65, 0x61, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x72, 0x65,
	0x70, 0x65, 0x61, 0x74, 0x73, 0x22, 0x18, 0x0a, 0x16, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x50, 0x75,
	0x6c, 0x6c, 0x55, 0x70, 0x73, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x18, 0x0a, 0x16, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x43, 0x79, 0x63, 0x6c, 0x69, 0x6e, 0x67, 0x56,
	0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x73, 0x0a, 0x15, 0x54, 0x72, 0x61,
	0x63, 0x6b, 0x43, 0x79, 0x63, 0x6c, 0x69, 0x6e, 0x67, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x72, 0x65, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x72, 0x65, 0x73, 0x22, 0x76,
	0x0a, 0x16, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x43, 0x72, 0x75, 0x6e, 0x63, 0x68, 0x65, 0x73, 0x56,
	0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x72,
	0x65, 0x70, 0x65, 0x61, 0x74, 0x73, 0x22, 0x19, 0x0a, 0x17, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x43,
	0x72, 0x75, 0x6e, 0x63, 0x68, 0x65, 0x73, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x74, 0x0a, 0x14, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x50, 0x75, 0x73, 0x68, 0x55, 0x70,
	0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a,
	0x07, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x73, 0x22, 0x18, 0x0a, 0x16, 0x54, 0x72, 0x61, 0x63, 0x6b,
	0x50, 0x75, 0x73, 0x68, 0x55, 0x70, 0x73, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x3d, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x4c, 0x69, 0x73, 0x74, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a,
	0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x61, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4c,
	0x69, 0x73, 0x74, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a,
	0x0d, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x69, 0x74, 0x79, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0x6f, 0x0a, 0x13, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x53, 0x74, 0x65, 0x70,
	0x73, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x61,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x65, 0x70, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73,
	0x74, 0x65, 0x70, 0x73, 0x22, 0x16, 0x0a, 0x14, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x53, 0x74, 0x65,
	0x70, 0x73, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x35, 0x0a, 0x0f,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x32, 0xbc, 0x07, 0x0a, 0x08, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x12, 0x8e, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x4c, 0x69, 0x73, 0x74, 0x56, 0x31, 0x12, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x29, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73,
	0x74, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x24, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x1e, 0x3a, 0x01, 0x2a, 0x22, 0x19, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f,
	0x67, 0x65, 0x74, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x2f, 0x6c, 0x69, 0x73,
	0x74, 0x12, 0x79, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x53, 0x74, 0x65, 0x70, 0x73, 0x56,
	0x31, 0x12, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x53, 0x74, 0x65, 0x70, 0x73, 0x56, 0x31, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x53, 0x74, 0x65,
	0x70, 0x73, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1e, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x18, 0x3a, 0x01, 0x2a, 0x22, 0x13, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31,
	0x2f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x2f, 0x73, 0x74, 0x65, 0x70, 0x73, 0x12, 0x81, 0x01, 0x0a,
	0x0e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x50, 0x75, 0x73, 0x68, 0x55, 0x70, 0x73, 0x56, 0x31, 0x12,
	0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x50, 0x75, 0x73, 0x68, 0x55, 0x70, 0x56, 0x31, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x50, 0x75, 0x73, 0x68,
	0x55, 0x70, 0x73, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x21, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x3a, 0x01, 0x2a, 0x22, 0x16, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76,
	0x31, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x2f, 0x70, 0x75, 0x73, 0x68, 0x2f, 0x75, 0x70, 0x73,
	0x12, 0x85, 0x01, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x43, 0x72, 0x75, 0x6e, 0x63, 0x68,
	0x65, 0x73, 0x56, 0x31, 0x12, 0x26, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x69, 0x74, 0x79, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x43, 0x72, 0x75, 0x6e, 0x63,
	0x68, 0x65, 0x73, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x2e, 0x54, 0x72,
	0x61, 0x63, 0x6b, 0x43, 0x72, 0x75, 0x6e, 0x63, 0x68, 0x65, 0x73, 0x56, 0x31, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x3a, 0x01, 0x2a,
	0x22, 0x16, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x2f,
	0x63, 0x72, 0x75, 0x6e, 0x63, 0x68, 0x65, 0x73, 0x12, 0x81, 0x01, 0x0a, 0x0e, 0x54, 0x72, 0x61,
	0x63, 0x6b, 0x43, 0x79, 0x63, 0x6c, 0x69, 0x6e, 0x67, 0x56, 0x31, 0x12, 0x25, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x2e, 0x54, 0x72, 0x61,
	0x63, 0x6b, 0x43, 0x79, 0x63, 0x6c, 0x69, 0x6e, 0x67, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x26, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x43, 0x79, 0x63, 0x6c, 0x69, 0x6e, 0x67,
	0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x20, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x1a, 0x3a, 0x01, 0x2a, 0x22, 0x15, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x74,
	0x72, 0x61, 0x63, 0x6b, 0x2f, 0x63, 0x79, 0x63, 0x6c, 0x69, 0x6e, 0x67, 0x12, 0x82, 0x01, 0x0a,
	0x0e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x50, 0x75, 0x6c, 0x6c, 0x55, 0x70, 0x73, 0x56, 0x31, 0x12,
	0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x50, 0x75, 0x6c, 0x6c, 0x55, 0x70, 0x73, 0x56, 0x31, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x50, 0x75, 0x6c,
	0x6c, 0x55, 0x70, 0x73, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x21,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x3a, 0x01, 0x2a, 0x22, 0x16, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x31, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x2f, 0x70, 0x75, 0x6c, 0x6c, 0x2f, 0x75, 0x70,
	0x73, 0x12, 0x8e, 0x01, 0x0a, 0x11, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x42, 0x65, 0x6e, 0x63, 0x68,
	0x50, 0x72, 0x65, 0x73, 0x73, 0x56, 0x31, 0x12, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x42, 0x65,
	0x6e, 0x63, 0x68, 0x50, 0x72, 0x65, 0x73, 0x73, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x29, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x42, 0x65, 0x6e, 0x63, 0x68, 0x50, 0x72, 0x65,
	0x73, 0x73, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x24, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x1e, 0x3a, 0x01, 0x2a, 0x22, 0x19, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31,
	0x2f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x2f, 0x62, 0x65, 0x6e, 0x63, 0x68, 0x2f, 0x70, 0x72, 0x65,
	0x73, 0x73, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_activity_activity_proto_rawDescOnce sync.Once
	file_activity_activity_proto_rawDescData = file_activity_activity_proto_rawDesc
)

func file_activity_activity_proto_rawDescGZIP() []byte {
	file_activity_activity_proto_rawDescOnce.Do(func() {
		file_activity_activity_proto_rawDescData = protoimpl.X.CompressGZIP(file_activity_activity_proto_rawDescData)
	})
	return file_activity_activity_proto_rawDescData
}

var file_activity_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_activity_activity_proto_goTypes = []interface{}{
	(*TrackBenchPressV1Response)(nil), // 0: proto.activity.TrackBenchPressV1Response
	(*TrackBenchPressV1Request)(nil),  // 1: proto.activity.TrackBenchPressV1Request
	(*TrackPullUpsV1Request)(nil),     // 2: proto.activity.TrackPullUpsV1Request
	(*TrackPullUpsV1Response)(nil),    // 3: proto.activity.TrackPullUpsV1Response
	(*TrackCyclingV1Response)(nil),    // 4: proto.activity.TrackCyclingV1Response
	(*TrackCyclingV1Request)(nil),     // 5: proto.activity.TrackCyclingV1Request
	(*TrackCrunchesV1Request)(nil),    // 6: proto.activity.TrackCrunchesV1Request
	(*TrackCrunchesV1Response)(nil),   // 7: proto.activity.TrackCrunchesV1Response
	(*TrackPushUpV1Request)(nil),      // 8: proto.activity.TrackPushUpV1Request
	(*TrackPushUpsV1Response)(nil),    // 9: proto.activity.TrackPushUpsV1Response
	(*GetActivityListV1Request)(nil),  // 10: proto.activity.GetActivityListV1Request
	(*GetActivityListV1Response)(nil), // 11: proto.activity.GetActivityListV1Response
	(*TrackStepsV1Request)(nil),       // 12: proto.activity.TrackStepsV1Request
	(*TrackStepsV1Response)(nil),      // 13: proto.activity.TrackStepsV1Response
	(*ActivityMessage)(nil),           // 14: proto.activity.ActivityMessage
}
var file_activity_activity_proto_depIdxs = []int32{
	14, // 0: proto.activity.GetActivityListV1Response.activity_list:type_name -> proto.activity.ActivityMessage
	10, // 1: proto.activity.Activity.GetActivityListV1:input_type -> proto.activity.GetActivityListV1Request
	12, // 2: proto.activity.Activity.TrackStepsV1:input_type -> proto.activity.TrackStepsV1Request
	8,  // 3: proto.activity.Activity.TrackPushUpsV1:input_type -> proto.activity.TrackPushUpV1Request
	6,  // 4: proto.activity.Activity.TrackCrunchesV1:input_type -> proto.activity.TrackCrunchesV1Request
	5,  // 5: proto.activity.Activity.TrackCyclingV1:input_type -> proto.activity.TrackCyclingV1Request
	2,  // 6: proto.activity.Activity.TrackPullUpsV1:input_type -> proto.activity.TrackPullUpsV1Request
	1,  // 7: proto.activity.Activity.TrackBenchPressV1:input_type -> proto.activity.TrackBenchPressV1Request
	11, // 8: proto.activity.Activity.GetActivityListV1:output_type -> proto.activity.GetActivityListV1Response
	13, // 9: proto.activity.Activity.TrackStepsV1:output_type -> proto.activity.TrackStepsV1Response
	9,  // 10: proto.activity.Activity.TrackPushUpsV1:output_type -> proto.activity.TrackPushUpsV1Response
	7,  // 11: proto.activity.Activity.TrackCrunchesV1:output_type -> proto.activity.TrackCrunchesV1Response
	4,  // 12: proto.activity.Activity.TrackCyclingV1:output_type -> proto.activity.TrackCyclingV1Response
	3,  // 13: proto.activity.Activity.TrackPullUpsV1:output_type -> proto.activity.TrackPullUpsV1Response
	0,  // 14: proto.activity.Activity.TrackBenchPressV1:output_type -> proto.activity.TrackBenchPressV1Response
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_activity_activity_proto_init() }
func file_activity_activity_proto_init() {
	if File_activity_activity_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_activity_activity_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackBenchPressV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_activity_activity_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackBenchPressV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_activity_activity_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackPullUpsV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_activity_activity_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackPullUpsV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_activity_activity_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackCyclingV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_activity_activity_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackCyclingV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_activity_activity_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackCrunchesV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_activity_activity_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackCrunchesV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_activity_activity_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackPushUpV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_activity_activity_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackPushUpsV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_activity_activity_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetActivityListV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_activity_activity_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetActivityListV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_activity_activity_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackStepsV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_activity_activity_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackStepsV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_activity_activity_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivityMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_activity_activity_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_activity_activity_proto_goTypes,
		DependencyIndexes: file_activity_activity_proto_depIdxs,
		MessageInfos:      file_activity_activity_proto_msgTypes,
	}.Build()
	File_activity_activity_proto = out.File
	file_activity_activity_proto_rawDesc = nil
	file_activity_activity_proto_goTypes = nil
	file_activity_activity_proto_depIdxs = nil
}
