// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.3
// source: activity/activity.proto

package activity

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Activity_GetActivityListV1_FullMethodName = "/proto.activity.Activity/GetActivityListV1"
	Activity_TrackStepsV1_FullMethodName      = "/proto.activity.Activity/TrackStepsV1"
)

// ActivityClient is the client API for Activity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ActivityClient interface {
	GetActivityListV1(ctx context.Context, in *GetActivityListV1Request, opts ...grpc.CallOption) (*GetActivityListV1Response, error)
	TrackStepsV1(ctx context.Context, in *TrackStepsV1Request, opts ...grpc.CallOption) (*TrackStepsV1Response, error)
}

type activityClient struct {
	cc grpc.ClientConnInterface
}

func NewActivityClient(cc grpc.ClientConnInterface) ActivityClient {
	return &activityClient{cc}
}

func (c *activityClient) GetActivityListV1(ctx context.Context, in *GetActivityListV1Request, opts ...grpc.CallOption) (*GetActivityListV1Response, error) {
	out := new(GetActivityListV1Response)
	err := c.cc.Invoke(ctx, Activity_GetActivityListV1_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) TrackStepsV1(ctx context.Context, in *TrackStepsV1Request, opts ...grpc.CallOption) (*TrackStepsV1Response, error) {
	out := new(TrackStepsV1Response)
	err := c.cc.Invoke(ctx, Activity_TrackStepsV1_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActivityServer is the server API for Activity service.
// All implementations should embed UnimplementedActivityServer
// for forward compatibility
type ActivityServer interface {
	GetActivityListV1(context.Context, *GetActivityListV1Request) (*GetActivityListV1Response, error)
	TrackStepsV1(context.Context, *TrackStepsV1Request) (*TrackStepsV1Response, error)
}

// UnimplementedActivityServer should be embedded to have forward compatible implementations.
type UnimplementedActivityServer struct {
}

func (UnimplementedActivityServer) GetActivityListV1(context.Context, *GetActivityListV1Request) (*GetActivityListV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActivityListV1 not implemented")
}
func (UnimplementedActivityServer) TrackStepsV1(context.Context, *TrackStepsV1Request) (*TrackStepsV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrackStepsV1 not implemented")
}

// UnsafeActivityServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActivityServer will
// result in compilation errors.
type UnsafeActivityServer interface {
	mustEmbedUnimplementedActivityServer()
}

func RegisterActivityServer(s grpc.ServiceRegistrar, srv ActivityServer) {
	s.RegisterService(&Activity_ServiceDesc, srv)
}

func _Activity_GetActivityListV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActivityListV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).GetActivityListV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_GetActivityListV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).GetActivityListV1(ctx, req.(*GetActivityListV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_TrackStepsV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackStepsV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).TrackStepsV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_TrackStepsV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).TrackStepsV1(ctx, req.(*TrackStepsV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Activity_ServiceDesc is the grpc.ServiceDesc for Activity service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Activity_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.activity.Activity",
	HandlerType: (*ActivityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetActivityListV1",
			Handler:    _Activity_GetActivityListV1_Handler,
		},
		{
			MethodName: "TrackStepsV1",
			Handler:    _Activity_TrackStepsV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "activity/activity.proto",
}
