// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.3
// source: auth/auth.proto

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Auth_AuthWithCredentialsV1_FullMethodName = "/proto.auth.Auth/AuthWithCredentialsV1"
	Auth_AuthWithAccessTokenV1_FullMethodName = "/proto.auth.Auth/AuthWithAccessTokenV1"
	Auth_RefreshTokensV1_FullMethodName       = "/proto.auth.Auth/RefreshTokensV1"
)

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthClient interface {
	AuthWithCredentialsV1(ctx context.Context, in *AuthWithCredentialsV1Request, opts ...grpc.CallOption) (*AccessRefreshTokens, error)
	AuthWithAccessTokenV1(ctx context.Context, in *AuthWithAccessTokenV1Request, opts ...grpc.CallOption) (*AuthWithAccessTokenV1Response, error)
	RefreshTokensV1(ctx context.Context, in *AccessRefreshTokens, opts ...grpc.CallOption) (*AccessRefreshTokens, error)
}

type authClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthClient(cc grpc.ClientConnInterface) AuthClient {
	return &authClient{cc}
}

func (c *authClient) AuthWithCredentialsV1(ctx context.Context, in *AuthWithCredentialsV1Request, opts ...grpc.CallOption) (*AccessRefreshTokens, error) {
	out := new(AccessRefreshTokens)
	err := c.cc.Invoke(ctx, Auth_AuthWithCredentialsV1_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) AuthWithAccessTokenV1(ctx context.Context, in *AuthWithAccessTokenV1Request, opts ...grpc.CallOption) (*AuthWithAccessTokenV1Response, error) {
	out := new(AuthWithAccessTokenV1Response)
	err := c.cc.Invoke(ctx, Auth_AuthWithAccessTokenV1_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) RefreshTokensV1(ctx context.Context, in *AccessRefreshTokens, opts ...grpc.CallOption) (*AccessRefreshTokens, error) {
	out := new(AccessRefreshTokens)
	err := c.cc.Invoke(ctx, Auth_RefreshTokensV1_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
// All implementations should embed UnimplementedAuthServer
// for forward compatibility
type AuthServer interface {
	AuthWithCredentialsV1(context.Context, *AuthWithCredentialsV1Request) (*AccessRefreshTokens, error)
	AuthWithAccessTokenV1(context.Context, *AuthWithAccessTokenV1Request) (*AuthWithAccessTokenV1Response, error)
	RefreshTokensV1(context.Context, *AccessRefreshTokens) (*AccessRefreshTokens, error)
}

// UnimplementedAuthServer should be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (UnimplementedAuthServer) AuthWithCredentialsV1(context.Context, *AuthWithCredentialsV1Request) (*AccessRefreshTokens, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthWithCredentialsV1 not implemented")
}
func (UnimplementedAuthServer) AuthWithAccessTokenV1(context.Context, *AuthWithAccessTokenV1Request) (*AuthWithAccessTokenV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthWithAccessTokenV1 not implemented")
}
func (UnimplementedAuthServer) RefreshTokensV1(context.Context, *AccessRefreshTokens) (*AccessRefreshTokens, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshTokensV1 not implemented")
}

// UnsafeAuthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServer will
// result in compilation errors.
type UnsafeAuthServer interface {
	mustEmbedUnimplementedAuthServer()
}

func RegisterAuthServer(s grpc.ServiceRegistrar, srv AuthServer) {
	s.RegisterService(&Auth_ServiceDesc, srv)
}

func _Auth_AuthWithCredentialsV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthWithCredentialsV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).AuthWithCredentialsV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_AuthWithCredentialsV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).AuthWithCredentialsV1(ctx, req.(*AuthWithCredentialsV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_AuthWithAccessTokenV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthWithAccessTokenV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).AuthWithAccessTokenV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_AuthWithAccessTokenV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).AuthWithAccessTokenV1(ctx, req.(*AuthWithAccessTokenV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_RefreshTokensV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessRefreshTokens)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).RefreshTokensV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_RefreshTokensV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).RefreshTokensV1(ctx, req.(*AccessRefreshTokens))
	}
	return interceptor(ctx, in, info, handler)
}

// Auth_ServiceDesc is the grpc.ServiceDesc for Auth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Auth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.auth.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthWithCredentialsV1",
			Handler:    _Auth_AuthWithCredentialsV1_Handler,
		},
		{
			MethodName: "AuthWithAccessTokenV1",
			Handler:    _Auth_AuthWithAccessTokenV1_Handler,
		},
		{
			MethodName: "RefreshTokensV1",
			Handler:    _Auth_RefreshTokensV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/auth.proto",
}
