// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: auth/auth.proto

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Auth_AuthWithCredentials_FullMethodName = "/proto.auth.Auth/AuthWithCredentials"
	Auth_AuthWithAccessToken_FullMethodName = "/proto.auth.Auth/AuthWithAccessToken"
	Auth_RefreshTokens_FullMethodName       = "/proto.auth.Auth/RefreshTokens"
)

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthClient interface {
	AuthWithCredentials(ctx context.Context, in *AuthWithCredentialsRequest, opts ...grpc.CallOption) (*AccessRefreshTokens, error)
	AuthWithAccessToken(ctx context.Context, in *AuthWithAccessTokenRequest, opts ...grpc.CallOption) (*AuthWithAccessTokenResponse, error)
	RefreshTokens(ctx context.Context, in *AccessRefreshTokens, opts ...grpc.CallOption) (*AccessRefreshTokens, error)
}

type authClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthClient(cc grpc.ClientConnInterface) AuthClient {
	return &authClient{cc}
}

func (c *authClient) AuthWithCredentials(ctx context.Context, in *AuthWithCredentialsRequest, opts ...grpc.CallOption) (*AccessRefreshTokens, error) {
	out := new(AccessRefreshTokens)
	err := c.cc.Invoke(ctx, Auth_AuthWithCredentials_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) AuthWithAccessToken(ctx context.Context, in *AuthWithAccessTokenRequest, opts ...grpc.CallOption) (*AuthWithAccessTokenResponse, error) {
	out := new(AuthWithAccessTokenResponse)
	err := c.cc.Invoke(ctx, Auth_AuthWithAccessToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) RefreshTokens(ctx context.Context, in *AccessRefreshTokens, opts ...grpc.CallOption) (*AccessRefreshTokens, error) {
	out := new(AccessRefreshTokens)
	err := c.cc.Invoke(ctx, Auth_RefreshTokens_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
// All implementations should embed UnimplementedAuthServer
// for forward compatibility
type AuthServer interface {
	AuthWithCredentials(context.Context, *AuthWithCredentialsRequest) (*AccessRefreshTokens, error)
	AuthWithAccessToken(context.Context, *AuthWithAccessTokenRequest) (*AuthWithAccessTokenResponse, error)
	RefreshTokens(context.Context, *AccessRefreshTokens) (*AccessRefreshTokens, error)
}

// UnimplementedAuthServer should be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (UnimplementedAuthServer) AuthWithCredentials(context.Context, *AuthWithCredentialsRequest) (*AccessRefreshTokens, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthWithCredentials not implemented")
}
func (UnimplementedAuthServer) AuthWithAccessToken(context.Context, *AuthWithAccessTokenRequest) (*AuthWithAccessTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthWithAccessToken not implemented")
}
func (UnimplementedAuthServer) RefreshTokens(context.Context, *AccessRefreshTokens) (*AccessRefreshTokens, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshTokens not implemented")
}

// UnsafeAuthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServer will
// result in compilation errors.
type UnsafeAuthServer interface {
	mustEmbedUnimplementedAuthServer()
}

func RegisterAuthServer(s grpc.ServiceRegistrar, srv AuthServer) {
	s.RegisterService(&Auth_ServiceDesc, srv)
}

func _Auth_AuthWithCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthWithCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).AuthWithCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_AuthWithCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).AuthWithCredentials(ctx, req.(*AuthWithCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_AuthWithAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthWithAccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).AuthWithAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_AuthWithAccessToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).AuthWithAccessToken(ctx, req.(*AuthWithAccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_RefreshTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessRefreshTokens)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).RefreshTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_RefreshTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).RefreshTokens(ctx, req.(*AccessRefreshTokens))
	}
	return interceptor(ctx, in, info, handler)
}

// Auth_ServiceDesc is the grpc.ServiceDesc for Auth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Auth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.auth.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthWithCredentials",
			Handler:    _Auth_AuthWithCredentials_Handler,
		},
		{
			MethodName: "AuthWithAccessToken",
			Handler:    _Auth_AuthWithAccessToken_Handler,
		},
		{
			MethodName: "RefreshTokens",
			Handler:    _Auth_RefreshTokens_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/auth.proto",
}
